# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
network: "se_resnext50"

# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
run_distribute: False
enable_profiling: False
data_path: "/home/niu/data/all/train"
# "/home/niu/data/all/train" for train
output_path: "./train_log_ckpt"
load_path: "./checkpoint_path/"
device_target: "GPU"
checkpoint_path: "./checkpoint/"
checkpoint_file_path: "/home/niu/project/MindsporeGoodsRecognition/se_resnext50/train/2021-10-31_time_14_47_27/ckpt_0/0-12_711.ckpt"

# ==============================================================================
# Training options
image_size: [128, 128]
num_classes: 2390
batch_size: 1024

# learning rate scheduler
lr: 0.2
lr_scheduler: "cosine_annealing"
lr_epochs:
  [30,60,90,120]
lr_gamma: 0.1
eta_min: 0
T_max: 150
max_epoch: 150
warmup_epochs: 1

# other hyperparameter
weight_decay: 0.0001
momentum: 0.9
is_dynamic_loss_scale: 0
loss_scale: 1024
label_smooth: 1
label_smooth_factor: 0.1
per_batch_size: 128

# save ckpt controller
ckpt_interval: 5
ckpt_save_max: 5
is_save_on_master: 1
rank_save_ckpt_flag: 0
outputs_dir: ""
log_path: "./output_log"

# Export options
device_id: 0
width: 224
height: 224
file_name: "se_resnext50"
file_format: "AIR"
result_path: ""
label_path: ""

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Dataset url for obs"
train_url: "Training output url for obs"
checkpoint_url: "The location of checkpoint for obs"
data_path: "Dataset path for local"
output_path: "Training output path for local; save ckpt and log"
load_path: "The location of checkpoint for obs"
device_target: "Target device type, available: [Ascend, CPU]"
enable_profiling: "Whether enable profiling while training, default: False"
num_classes: "Class for dataset"
batch_size: "Batch size for training and evaluation"
epoch_size: "Total training epochs."
keep_checkpoint_max: "keep the last keep_checkpoint_max checkpoint"
checkpoint_path: "The location of the checkpoint file."
checkpoint_file_path: "The location of the checkpoint file."
